version: '3.4'
services:
  redis:
    image: redis
    container_name: nft-api-cache
    command: redis-server
    ports:
      - '6379:6379'
    expose:
      - '6379'
  db:
    image: mysql:5.7
    container_name: nft-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'


volumes:
  my-db:
